name: search-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - ambertools=24.8
  - arpack=3.9.1
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - contourpy=1.3.2
  - cycler=0.12.1
  - fftw=3.3.10
  - fonttools=4.61.1
  - freetype=2.14.1
  - hdf4=4.2.15
  - hdf5=1.14.4
  - icu=75.1
  - joblib=1.5.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libboost=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libcxx=21.1.7
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libnetcdf=4.9.2
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - lz4-c=1.10.0
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf-fortran=4.6.1
  - openjpeg=2.5.3
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parmed=4.3.0
  - perl=5.32.1
  - pip=25.3
  - pthread-stubs=0.4
  - pyparsing=3.2.5
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - tk=8.6.15
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxt=1.3.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - amberutils==21.0
      - biopython==1.86
      - catboost==1.2.8
      - edgembar==3.0
      - graphviz==0.21
      - lightgbm==4.6.0
      - mmpbsa-py==16.0
      - narwhals==2.13.0
      - numpy==1.26.4
      - packmol-memgen==2025.1.29
      - pdb4amber==22.0
      - pillow==12.0.0
      - plotly==6.5.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - sander==22.0
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.3
      - xgboost==3.0.4
